name: Run server.js

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes (optional)

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start server in background
        run: node server.js &

      - name: Wait for server to start
        run: sleep 5

      - name: Curl proxy endpoint
        run: curl http://localhost:3000/prices
