name: Fetch GG.deals Data

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:        # manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl to fetch data
        run: |
          curl 'https://gg.deals/us/games/chartHistoricalData/375527/?showKeyshops=1' \
            -H 'accept: application/json, text/javascript, */*; q=0.01' \
            -H 'referer: https://gg.deals/game/ea-sports-college-football-26-xbox-series/' \
            -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36'
