name: Fetch GG.deals Data with Puppeteer

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch: # manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run Puppeteer fetch script
        run: node fetch-ggdeals.js
