name: Scrape GG.deals

on:
  workflow_dispatch:

jobs:
  fetch-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Run fetch script
        run: node fetch-ggdeals.js
